"""Add original_filename to Report model

Revision ID: 2763455ca8d0
Revises: 0001_add_audio_file_path
Create Date: 2025-11-07 19:57:52.310123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2763455ca8d0'
down_revision: Union[str, Sequence[str], None] = '0001_add_audio_file_path'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('original_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'original_filename')
    # ### end Alembic commands ###
