"""Add original_filename to Report model

Revision ID: 78241e41fccb
Revises: 2763455ca8d0
Create Date: 2025-11-07 19:59:59.941718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78241e41fccb'
down_revision: Union[str, Sequence[str], None] = '2763455ca8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Column already exists from previous migration, no changes needed
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'original_filename')
    # ### end Alembic commands ###
