"""add language to chat_sessions

Revision ID: 9971bb4842e6
Revises: 9f1b_add_mime_and_thumbnail_to_reports
Create Date: 2026-06-23 23:03:09.249061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9971bb4842e6'
down_revision: Union[str, Sequence[str], None] = '9f1b_add_mime_and_thumbnail_to_reports'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('language', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('report_type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('raw_text', sa.TEXT(), nullable=True),
    sa.Column('summary_text', sa.TEXT(), nullable=True),
    sa.Column('original_file_path', sa.VARCHAR(), nullable=True),
    sa.Column('original_filename', sa.VARCHAR(), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(), nullable=True),
    sa.Column('audio_file_path', sa.VARCHAR(), nullable=True),
    sa.Column('thumbnail_path', sa.VARCHAR(), nullable=True),
    sa.Column('chat_session_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('audio_file_path', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    # ### end Alembic commands ###
