# app/main.py autogenerated
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import RedirectResponse
from app.db import models, database
from app.api import api_router
from app.pages import page_router

# Create all database tables on startup
# In a real production app, you'd use migrations (e.g., Alembic)
models.Base.metadata.create_all(bind=database.engine)

app = FastAPI(title="FastAPI Med Analyzer")

# Mount the static files directory (for CSS/JS)
app.mount("/static", StaticFiles(directory="app/static"), name="static")

# Mount the media files directory (for user uploads and audio)
app.mount("/media", StaticFiles(directory="media"), name="media")

# Include the API and Page routers
app.include_router(api_router, prefix="/api/v1")
app.include_router(page_router, tags=["Pages"])

@app.get("/", include_in_schema=False)
def read_root():
    """Redirects root to the login page."""
    return RedirectResponse(url="/login")

@app.on_event("startup")
def on_startup():
    """Log that the AI services are being loaded."""
    import logging
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    logger = logging.getLogger(__name__)

    logger.info("FastAPI app starting up...")
    logger.info("Loading AI models (MedGemma, Kokoro, etc.)...")

    # NOTE: we intentionally avoid downloading models or importing the
    # heavyweight `app.services` module during FastAPI startup. Importing the
    # services triggers model initialization and file writes (model caches)
    # which can cause file-watchers (uvicorn/WatchFiles) to reload the app
    # repeatedly in development. Instead, models are either:
    #  - downloaded ahead-of-time by running `python download_models.py` (recommended),
    #  - or initialized lazily the first time a request needs them.
    logger.info("Skipping automatic model downloads at startup.")
    logger.info("To pre-download models before running the server run: python download_models.py")
    logger.info("AI services will be loaded lazily on first use.")
