# app/main.py autogenerated
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from fastapi.responses import RedirectResponse
from app.db import models, database
from app.api import api_router
from app.pages import page_router

# Create all database tables on startup
# In a real production app, you'd use migrations (e.g., Alembic)
models.Base.metadata.create_all(bind=database.engine)

app = FastAPI(title="FastAPI Med Analyzer")

# Mount the static files directory (for CSS/JS)
app.mount("/static", StaticFiles(directory="app/static"), name="static")

# Mount the media files directory (for user uploads and audio)
app.mount("/media", StaticFiles(directory="media"), name="media")

# Include the API and Page routers
app.include_router(api_router, prefix="/api/v1")
app.include_router(page_router, tags=["Pages"])

@app.get("/", include_in_schema=False)
def read_root():
    """Redirects root to the login page."""
    return RedirectResponse(url="/login")

@app.on_event("startup")
def on_startup():
    """Log that the AI services are being loaded."""
    import logging
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    logger = logging.getLogger(__name__)

    logger.info("FastAPI app starting up...")
    logger.info("Loading AI models (MedGemma, Kokoro, etc.)...")

    try:
        # Check and download models if needed
        logger.info("Checking and downloading models...")
        from download_models import check_and_download_models
        check_and_download_models()
        logger.info("Models downloaded successfully.")

        # Import services to trigger model loading
        logger.info("Loading AI services...")
        from app.services import summarizer_service, parser_service, tts_service
        logger.info("AI services loaded successfully.")
    except Exception as e:
        logger.error(f"Failed to load AI services: {e}", exc_info=True)
        raise
